#!/bin/bash
set -e

cd /var/www/html

echo "==> [1/8] Runtime tuning and writable directories"

# PHP-FPM's packaged pool allows 5 concurrent requests. That is a floor chosen so the
# image starts anywhere, not a value suited to any particular host — on a machine with
# real memory it means a handful of slow connections can occupy every worker while the
# hardware sits idle. install.sh sizes these from the actual CPU and RAM and writes them
# to .env; compose passes them in. Written here rather than baked into the image so a
# retune is a restart, not a rebuild.
FPM_MAX_CHILDREN="${PHP_FPM_MAX_CHILDREN:-5}"
FPM_START_SERVERS="${PHP_FPM_START_SERVERS:-2}"
FPM_MIN_SPARE="${PHP_FPM_MIN_SPARE:-1}"
FPM_MAX_SPARE="${PHP_FPM_MAX_SPARE:-3}"

cat > /usr/local/etc/php-fpm.d/zz-tuning.conf <<FPMCONF
[www]
pm = dynamic
pm.max_children = ${FPM_MAX_CHILDREN}
pm.start_servers = ${FPM_START_SERVERS}
pm.min_spare_servers = ${FPM_MIN_SPARE}
pm.max_spare_servers = ${FPM_MAX_SPARE}
; Recycle workers periodically so a slow leak in any one request cannot accumulate
; across the life of the container.
pm.max_requests = 500
FPMCONF

echo "    PHP-FPM: max_children=${FPM_MAX_CHILDREN} start=${FPM_START_SERVERS} spare=${FPM_MIN_SPARE}-${FPM_MAX_SPARE}"
if [ "$FPM_MAX_CHILDREN" = "5" ]; then
    echo "    (still the packaged default — run ./install.sh to size this for this server)"
fi

mkdir -p bootstrap/cache \
    storage/app/public \
    storage/app/public/uploads \
    storage/framework/cache/data \
    storage/framework/cache/purifier \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs

# bootstrap/cache and storage live on the host bind mount and survive rebuilds.
# Stale compiled config/routes/views from an older code version are a common cause
# of 500 errors after a deploy, so wipe them on every boot.
rm -f bootstrap/cache/config.php \
      bootstrap/cache/routes-*.php \
      bootstrap/cache/events.php \
      bootstrap/cache/services.php \
      bootstrap/cache/packages.php
rm -rf storage/framework/views/*

chown -R www-data:www-data storage bootstrap/cache
chmod -R 775 storage bootstrap/cache

echo "==> [2/8] Composer dependencies"
# vendor/ lives on the host bind mount and survives rebuilds — but so does an *outdated*
# vendor/. Installing only when vendor/autoload.php is absent means a newly required
# package never arrives on an existing deployment, and the first request to hit the
# missing class 500s. So stamp the hash of composer.json after every successful install
# and reinstall whenever the two disagree.
COMPOSER_STAMP="storage/.composer-installed"
COMPOSER_HASH="$(md5sum composer.json | awk '{ print $1 }')"

if [ ! -f vendor/autoload.php ]; then
    COMPOSER_REASON="vendor/ is missing"
elif [ ! -f "$COMPOSER_STAMP" ]; then
    COMPOSER_REASON="no install stamp — vendor/ predates this check"
elif [ "$(cat "$COMPOSER_STAMP")" != "$COMPOSER_HASH" ]; then
    COMPOSER_REASON="composer.json changed since the last install"
else
    COMPOSER_REASON=""
fi

if [ -n "$COMPOSER_REASON" ]; then
    echo "    Installing: $COMPOSER_REASON."

    # `composer install` installs strictly from composer.lock and refuses to run when
    # the lock does not satisfy composer.json. composer.lock is not committed, so the
    # one on the host bind mount was generated by an earlier boot and knows nothing
    # about a package added since — exactly the situation this whole step exists to
    # handle. Fall back to `update`, which re-resolves and rewrites the lock.
    if composer install --no-dev --optimize-autoloader --no-interaction --no-progress; then
        echo "    Composer install OK."
    else
        echo "    Lock file is out of date with composer.json; re-resolving."
        # No `|| true`: if this fails too, set -e aborts the boot. A half-installed
        # vendor/ produces "Class not found" on every page, which is far harder to
        # diagnose from the logs than a container that refuses to start.
        composer update --no-dev --optimize-autoloader --no-interaction --no-progress
        echo "    Composer update OK. composer.lock has been refreshed on the host —"
        echo "    commit it to make future deploys reproducible."
    fi

    # Only reached when one of the two succeeded, so the stamp can never claim more
    # than what is actually on disk.
    echo "$COMPOSER_HASH" > "$COMPOSER_STAMP"
else
    echo "    vendor/ matches composer.json, skipping."
fi

echo "==> [3/8] Environment file"
if [ ! -f .env ]; then
    echo "    .env missing, creating from .env.example"
    cp .env.example .env
fi
# .env holds the database password, APP_KEY, the payment gateway's merchant secret
# and the SMTP password. Under the default umask it is created 0644 — readable by
# every user on the host, since this file is bind-mounted from there. Tightened on
# every start, not just on creation, because a .env copied in by hand or restored
# from a backup arrives with whatever mode it had.
chmod 600 .env 2>/dev/null || echo "    WARNING: could not chmod 600 .env — it holds secrets"

# Match APP_KEY= with nothing (or only whitespace/CR) after it.
if grep -Eq '^APP_KEY=[[:space:]]*$' .env; then
    echo "    Generating APP_KEY"
    php artisan key:generate --force --no-interaction
else
    echo "    APP_KEY present."
fi

echo "==> [4/8] Public storage symlink"
# Uploaded images are written to storage/app/public/uploads and served from
# /storage/uploads/..., which only resolves through the public/storage symlink.
# public/ is on the host bind mount, so the link persists across restarts — check for
# it rather than re-running storage:link, which reports the existing link as an error.
if [ -L public/storage ]; then
    echo "    Symlink present."
elif [ -e public/storage ]; then
    echo "    !! public/storage exists but is not a symlink. Uploaded images will 404."
elif php artisan storage:link --no-interaction; then
    echo "    Symlink created."
else
    echo "    !! storage:link failed. Uploaded images will 404 until this is fixed."
fi

echo "==> [5/8] Waiting for PostgreSQL"
for i in $(seq 1 60); do
    if php -r '
        $h = getenv("DB_HOST") ?: "postgres";
        $p = getenv("DB_PORT") ?: "5432";
        $c = @fsockopen($h, (int) $p, $e, $s, 2);
        exit($c ? 0 : 1);
    '; then
        echo "    PostgreSQL reachable after ${i}s."
        break
    fi
    if [ "$i" = "60" ]; then
        echo "    !! PostgreSQL unreachable after 60s. Continuing, but the site will error."
    fi
    sleep 1
done

echo "==> [6/8] Migrations and seed"
# Deliberately NOT silenced: a failed migration means the settings table is missing,
# which turns every page into a 500. The operator needs to see it in `docker logs`.
if php artisan migrate --force --no-interaction; then
    echo "    Migrations OK."
    # DatabaseSeeder is idempotent (firstOrCreate), so it is safe on every boot:
    # it creates the default admin and settings rows only when they are absent and
    # never overwrites values changed from the admin UI.
    if php artisan db:seed --force --no-interaction; then
        echo "    Seed OK."
    else
        echo "    !! Seeding failed. The admin account may not exist."
    fi
else
    echo "    !! MIGRATIONS FAILED. The site will return 500 until this is fixed."
fi

echo "==> [7/8] Precompiling Blade views"
# This is not just a warm cache, it closes a race that took the site down.
#
# Blade writes each compiled view with file_put_contents() and then immediately
# includes it. When several PHP-FPM workers get their first request for the same
# uncompiled view at once, one worker can include the file while another is still
# writing it. The truncated include is a parse error ("unexpected end of file"),
# and OPcache then caches that broken compilation. Because the file's mtime never
# changes afterwards, OPcache never revalidates it, so every later request keeps
# getting the broken copy — `view:clear` and container rebuilds do not help.
#
# Compiling every view here, in one process, before FPM accepts any traffic, means
# workers only ever include files that are already complete on disk.
if php artisan view:cache --no-interaction; then
    echo "    Views precompiled."
else
    echo "    !! View precompilation failed — see the error above."
fi

# Syntax-check the generated PHP. A Blade template can compile "successfully" into
# PHP that does not parse — a literal "@context" in JSON-LD, for example, is the real
# @context directive and expands to an unclosed if(). That only shows up as a 500 at
# request time, so check it here where it is visible in the startup log.
BROKEN=0
for VIEW in storage/framework/views/*.php; do
    [ -e "$VIEW" ] || continue
    if ! php -l "$VIEW" >/dev/null 2>&1; then
        BROKEN=$((BROKEN + 1))
        echo "    !! Compiled view does not parse: $VIEW"
        php -l "$VIEW" 2>&1 | head -2 | sed 's/^/       /'
        grep -o 'PATH .* ENDPATH' "$VIEW" | sed 's/^/       source: /'
    fi
done
if [ "$BROKEN" -eq 0 ]; then
    echo "    All compiled views parse cleanly."
else
    echo "    !! $BROKEN compiled view(s) are broken — those pages will return 500."
fi

echo "==> [8/8] Admin frontend assets"
# The built SPA is committed to the repository under public/admin-assets/, so a normal
# deploy needs no Node toolchain at all. We only fall back to building when the assets
# are genuinely missing, and we never hide a failure behind `|| true`.
if [ -f public/admin-assets/index.html ]; then
    echo "    Prebuilt admin assets found."

    # A committed bundle can fall behind the source it was built from, and nothing else
    # would notice: the backend keeps working, the admin just silently runs old code.
    # docker/php/spa-stamp.sh hashes the SPA source; the build writes that hash next to
    # the bundle. Comparing them turns a stale deploy into a visible line here.
    if [ -f public/admin-assets/.build-stamp ] && [ -f docker/php/spa-stamp.sh ]; then
        WANT="$(sh docker/php/spa-stamp.sh 2>/dev/null || echo unknown)"
        HAVE="$(cat public/admin-assets/.build-stamp)"
        if [ "$WANT" = "unknown" ]; then
            echo "    (could not verify the bundle is current)"
        elif [ "$WANT" = "$HAVE" ]; then
            echo "    Bundle matches the SPA source."
        else
            echo "    !! STALE BUNDLE: public/admin-assets/ was built from different source."
            echo "    !! The admin will run outdated code. Rebuild and commit it:"
            echo "    !!   cd admin-frontend && npm install && npm run build"
            echo "    !!   sh docker/php/spa-stamp.sh > public/admin-assets/.build-stamp"
        fi
    fi
elif [ -d admin-frontend ] && command -v npm >/dev/null 2>&1; then
    echo "    Admin assets missing. Building in the background; watch 'docker logs -f cardshop-app'."
    (
        cd admin-frontend
        if NODE_OPTIONS="--max-old-space-size=1536" npm install --no-audit --no-fund \
           && NODE_OPTIONS="--max-old-space-size=1536" npm run build; then
            cd /var/www/html
            sh docker/php/spa-stamp.sh > public/admin-assets/.build-stamp 2>/dev/null || true
            echo "==> Admin frontend build SUCCEEDED."
        else
            echo "==> !! Admin frontend build FAILED (most likely out of memory)."
            echo "==> !! Build it on a machine with more RAM and commit public/admin-assets/."
        fi
    ) &
else
    echo "    !! Admin assets missing and npm unavailable. /admin will show the fallback page."
fi

echo "==> Starting PHP-FPM"
exec docker-php-entrypoint "$@"
